Fix syntax error in waagent
broken by 001_resolv_conf.patch from waagent commit ed0990ef50230bbfcd39a1b513063445fa22b13c

File "/usr/sbin/waagent", line 2342, in Deprovision
    fileBlackList.append(os.listdir(LibDir) + '/etc/resolv.conf')
TypeError: can only concatenate list (not "str") to list

changed from:
fileBlackList.append(os.listdir(LibDir) + '/etc/resolv.conf')
changed to:
fileBlackList.extend(os.listdir(LibDir) + ['/etc/resolv.conf'])